version: "3.8"
services:
  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  postgres_data:
