version: "3.8"
services:
  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  database:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  postgres_data:
